### ISSUE TITLE
结果

### ISSUE THREAD

**Issue by KobeDavid** [uncbiag/SegNext#3]
你好，能分享一下你的训练结果和测试结果吗？

**Comment by KobeDavid** [comment]
@qinliuliuqin

**Comment by qinliuliuqin** [comment]
@KobeDavid 请具体一点，那部分实验的结果？具体指的是什么结果？

**Comment by KobeDavid** [comment]
执行run_eval.sh和run_train.sh文件的结果

**Comment by KobeDavid** [comment]
@qinliuliuqin

**Comment by KobeDavid** [comment]
ModuleNotFoundError: No module named 'segnext',运行run_train.sh,出现这个问题是什么错误

**Comment by qinliuliuqin** [comment]
@KobeDavid 我没有遇到这个错误，你可以尝试把SegNext的路径加到Python path里。

**Comment by KobeDavid** [comment]
@qinliuliuqin 执行run_eval.sh和run_train.sh文件的结果，能分享一下吗？

**Comment by qinliuliuqin** [comment]
@KobeDavid 运行run_train.sh 得到的是模型，已上传并提供dowload脚本; 运行run_eval.sh得到的是Table 1中的量化结果，也已经写在github上了。

**Comment by KobeDavid** [comment]
我运行dowload脚本时有超时的错误，是网络的问题吗？

**Comment by KobeDavid** [comment]
> @KobeDavid 请具体一点，那部分实验的结果？具体指的是什么结果？

就是在你的电脑上执行run_eval.sh和run_train.sh文件的结果，截个图分享一下，欧克吗？

**Comment by KobeDavid** [comment]
@qinliuliuqin

**Comment by qinliuliuqin** [comment]
你应该首先应该尝试解决 ModuleNotFoundError，我已经告诉你可能的解决方案了。模型无法下载可能是因为保存在谷歌网盘的原因，你科学上网之后应该就可以了? 以下是正常训练时的输出，训练过程中模型会自动保存。

![Screenshot from 2024-06-18 22-33-32](https://github.com/uncbiag/SegNext/assets/57234075/011a2dcd-2c5d-4a2a-98ef-9f2b1f412eb6)

**Comment by KobeDavid** [comment]
谢谢，我已经解决了

**Comment by KobeDavid** [comment]
ok,谢谢，那个可视化结果有吗？分享一下欧克不

**Comment by KobeDavid** [comment]
@qinliuliuqin

**Comment by KobeDavid** [comment]
@qinliuliuqin 你好，分割的结果在哪里看呢
