### ISSUE TITLE
NoC (Number of Clicks) for SAM and SAM-HQ 

### ISSUE THREAD

**Issue by ChenyiZhang007** [uncbiag/SegNext#4]
how the NoC (Number of Clicks) for SAM and SAM-HQ is tested,  is the get_next_point() function used during testing the same as in segnext?
or any existing code available?

**Comment by ChenyiZhang007** [comment]
thanks a lot

**Comment by Z-MU-Z** [comment]
Hi, Thanks for your wonderful work! I also run the eval_sam scripts, my results is below
NoC@90 =  5.147826086956521                                                                                                              
NoC@95 =  10.785507246376811
NoF@95 =  150
5-mIoU =  0.9091643193449243,
why there is a little difference

**Comment by qinliuliuqin** [comment]
@qinliuliuqin The results may differ slightly given different versions of PyTorch and other packages. Did you use python=3.10, torch=2.2.0, torchvision=0.17.0?
