### ISSUE TITLE
finetuning on HQSeg-44K

### ISSUE THREAD

**Issue by ChenyiZhang007** [uncbiag/SegNext#5]
‘’We train our models on COCO+LVIS for 90 epochs with batch size 16 and fine-tune the models on HQSeg-44K for an additional epoch.‘’
Does this mean that finetuning on HQSeg-44K only requires one epoch, making the total training amount 91 epochs?

**Comment by qinliuliuqin** [comment]
Yes. Finetuning on HQSeg-44K is very time consuming, and we found 1 epoch was enough to achieve good performance.

**Comment by ChenyiZhang007** [comment]
Thanks
