### ISSUE TITLE
Name Conflicts

### ISSUE THREAD

**Issue by lxtGH** [uncbiag/SegNext#7]
**The model name is the same as previous work published two years ago.**

SegNext: https://arxiv.org/abs/2209.08575

It is funny that this CVPR paper does even cite and mention that work.

**Comment by lxtGH** [comment]
搞笑论文

**Comment by qinliuliuqin** [comment]
Thanks for pointing out. I can name my project whatever I choose and am not required to cite a unrelated paper even it has the same name.

**Comment by qinliuliuqin** [comment]
BTW, Our method is SegNext, not SegNeXt.

**Comment by lxtGH** [comment]
> Thanks for pointing out. I can name my project whatever I choose and am not required to cite a unrelated paper even it has the same name.

Sure, semantic segmentation has no relationship with interactive segmentation. 哈哈哈哈哈哈哈

**Comment by lxtGH** [comment]
> BTW, Our method is SegNext, not SegNeXt.

Funny 哈哈哈哈哈哈哈

**Comment by qinliuliuqin** [comment]
> > Thanks for pointing out. I can name my project whatever I choose and am not required to cite a unrelated paper even it has the same name.
> 
> Sure, semantic segmentation has no relationship with interactive segmentation. 哈哈哈哈哈哈哈

No, we cited two representative semantic segmentation papers in the high-quality interactive segmentation section of the Related Work. As authors, we have the freedom to choose the papers we reference. You are welcome to challenge our choices next time as a reviewer. : D

**Comment by qinliuliuqin** [comment]
> > Thanks for pointing out. I can name my project whatever I choose and am not required to cite a unrelated paper even it has the same name.
> 
> Sure, semantic segmentation has no relationship with interactive segmentation. 哈哈哈哈哈哈哈

If you're the real reference police, I suggest heading over to SegNeXt's GitHub and asking them why interactive segmentation papers are on their 'most wanted' list! hahaha

**Comment by qinliuliuqin** [comment]
To potential readers: we acknowledge the name clash with SegNeXt and appreciate those who pointed it out. When we named our project last year, prior to our CVPR submission, we were aware of ConvNeXt and SegNet but not SegNeXt. We may add a footnote to clarify the distinction, reference more related papers, and highlight the differences.
